//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationForm
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("First Name:")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("Other Name:")]
        public string OtherName { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("Investor Email:")]
        public string InvestorEmail { get; set; }
        [Required(ErrorMessage = "Valid email Required please")]
        [DisplayName("Age:")]
        public string Age { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("Phone Number:")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("Year Of Experience:")]
        public Nullable<int> YearOfExperience { get; set; }
        [Required(ErrorMessage = "Field Required please")]
        [DisplayName("Password:")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DisplayName("Comfirm Password:")]
        [DataType(DataType.Password)]
        public string ComfirmPassword { get; set; }
        [DisplayName("Amount:")]
        public Nullable<int> Amount { get; set; }
        [DisplayName("Upload Screenshort:")]
        public string Upload_Screenshort { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
